---
- hosts: all
  become: true
  pre_tasks:
     
  - name: install updated for fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"    
    
  - name: Install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"    

  - name: create user
    tags: always
    ansible.builtin.user:
      name: simone
      group: root  
  
  - name: add sudoers file for simone
    tags: always
    ansible.builtin.copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440    

  - name: add ssh keys for simone user
    tags: always
    ansible.posix.authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG4RA2Bk53dW7sd7pYqDQA/utBBepZ1C725UhaB+zqON t816343@ubuntu-ws"  

- hosts: web_servers
  become: yes
  tasks:
  - name: install apache on web servers (ubuntu)
    tags: apache, ubuntu
    ansible.builtin.apt:
      name:
       - apache2
       - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"     

  - name: install apache on web servers (fedora)
    tags: apache, fedora 
    ansible.builtin.dnf:
      name: httpd
    when: ansible_distribution == "Fedora"    

  - name: copy html file for site
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: default_site.html     
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  
  
  - name: ensure apache is running (Ubuntu)
    tags: apache, ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"    

  - name:  ensure apache is running (fedora)
    tags: apache, ubuntu
    ansible.builtin.service:
       name: httpd
       state: started     
    when: ansible_distribution == "Fedora"

- hosts: db_Servers
  tags: db, fedora
  become: yes
  tasks:
  - name: install mariadb package on db servers
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"     
